services:
  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --enable-feature=remote-write-receiver
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro

  k6:
    image: grafana/k6:0.50.0
    container_name: k6
    command: run -o experimental-prometheus-rw=http://prometheus:9090/api/v1/write /scripts/01-smoke.js
    volumes:
      - ./scripts:/scripts:ro
    depends_on:
      - prometheus
